export const topics = {
    "fitness at home": {
      "Hook Video": [
        { type: '  voiceover', text: "  Tired of spending hours at the gym with little to show for it? 🏋️‍♂️" },
        { type: ' onscreen', text: "  Home Workout Revolution 💥" },
        { type: ' voiceover', text: "  What if you could torch fat, build muscle, and transform... without leaving your living room? 🏡" },
        { type: ' scene', text: "  Fast cuts: Push-ups on carpet, jump squats next to sofa, climbers in cozy living room." },
        { type: ' voiceover', text: "  20 minutes a day. No equipment.  Just results . " },
        { type: ' onscreen', text: "  No Gym? No Problem. ✅" },
        { type: ' voiceover', text: "  Fitness isn’t about fancy gear — it’s about commitment. 💥" },
        { type: ' scene', text: "  Sweaty man laughing, giving high-five to toddler after home workout." },
        { type: ' voiceover', text: "  Ready to build your dream body? Let's get started! 🚀" },
        { type: ' cta', text: "  Follow for daily home fitness routines!" },
      ],
      "Value Drop": [
        { type: '  voiceover ', text: " Struggling to stay consistent with fitness? Here's why home workouts change the game. 🧠" },
        { type: '  onscreen', text: " No Commute. No Excuses. 🏡" },
        { type: ' voiceover', text: " Studies show 20-minute bodyweight sessions burn just as much fat as an hour at the gym. 🔥" },
        { type: ' scene', text: " Split-screen: One side lifting heavy at gym, other doing fast home bodyweight drills." },
        { type: ' voiceover', text: " Consistency is king. When it's easier, you'll show up more. 👑" },
        { type: ' onscreen', text: " Small Changes → Big Results ✅" },
        { type: ' voiceover', text: "Y ou don't need a gym. You need a system that fits your life." },
        { type: ' scene', text: " Morning shot: Woman doing yoga on balcony with sun rising." },
        { type: ' voiceover', text: " Imagine what 90 days of daily movement could do for you." },
        { type: ' cta', text: " Follow for realistic home fitness tips!" },
      ],
    },
  
    "skin care for men": {
      "Hook Video": [
        { type: '   voiceover', text: " Think skincare is just for women? Think again, king. 👑" },
        { type: '  onscreen', text: " Men’s Skincare Revolution 🧴" },
        { type: ' voiceover', text: " Confidence starts with clear, healthy skin. ✨" },
        { type: ' scene', text: " Man examining his face in the mirror under bright morning light." },
        { type: ' voiceover', text: " Harsh soaps wreck your face. Gentle, daily care builds it stronger." },
        { type: ' onscreen', text: " Invest in Your First Impression. 💥" },
        { type: ' voiceover', text: " Smooth skin, clean beard lines — it’s not optional anymore." },
        { type: ' scene', text: " Applying moisturizer carefully, lined up beard close-up shot." },
        { type: ' voiceover', text: " Command respect. Start with your reflection." },
        { type: ' cta', text: " Follow for no-BS skincare tips for men!" },
      ],
      "Value Drop": [
        { type: '  voiceover', text: "Want better skin but overwhelmed by routines? Here’s the 60-second fix. ⏱" },
        { type: ' onscreen', text: "The 3-Step Gamechanger Routine ✅" },
        { type: ' voiceover', text: "Step 1: Cleanse daily with a gentle face wash. No exceptions. 🧼" },
        { type: ' scene', text: "Slow-mo: man splashing cold water on face, smiling naturally." },
        { type: ' voiceover', text: "Step 2: Moisturize to prevent aging and dryness. 🧴" },
        { type: ' onscreen', text: "Stay Fresh. Stay Sharp. 🧠" },
        { type: ' voiceover', text: "Step 3: SPF daily. Protect your future face. 🛡" },
        { type: ' scene', text: "Applying SPF while walking confidently outside in sun." },
        { type: ' voiceover', text: "Simple. Powerful. Unstoppable." },
        { type: ' cta', text: "Follow to level up your skin game! ✨" },
      ],
    },
  
    "making money online": {
      "Hook Video": [
        { type: ' voiceover', text: "Still trading time for money? There’s a smarter way. 💻💰" },
        { type: ' onscreen', text: "The Digital Income Shift 🌍" },
        { type: ' voiceover', text: "While you're watching this... someone just made $200 from their laptop. 📈" },
        { type: ' scene', text: "Laptop screen glowing late night, PayPal or Stripe notification popping up." },
        { type: ' voiceover', text: "Passive income is real — if you know where to look." },
        { type: ' onscreen', text: "Skills → Systems → Freedom 🧠" },
        { type: ' voiceover', text: "Freelancing, e-commerce, AI content — the new gold rush is online." },
        { type: ' scene', text: "Typing fast on laptop; sipping coffee at beach cafe." },
        { type: ' voiceover', text: "Question is: Will you watch or participate?" },
        { type: ' cta', text: "Follow for online income breakdowns!" },
      ],
      "Value Drop": [
        { type: ' voiceover', text: "Three proven online income streams you can start today. 🚀" },
        { type: ' onscreen', text: "Digital Hustles That Work 🔥" },
        { type: ' voiceover', text: "1. Freelance writing — companies pay for great words. ✍️" },
        { type: ' scene', text: "Freelancer writing at laptop in cozy minimalist workspace." },
        { type: ' voiceover', text: "2. Dropshipping — sell products without touching inventory. 📦" },
        { type: ' onscreen', text: "Automation = Freedom ✅" },
        { type: ' voiceover', text: "3. AI content creation — leverage tools to create at scale. 🤖" },
        { type: ' scene', text: "Over-the-shoulder view of editing a video using AI tools." },
        { type: ' voiceover', text: "Start small. Scale smart. Compound results." },
        { type: ' cta', text: "Follow for step-by-step online guides!" },
      ],
    },
  "focus and discipline": {
  "Hook Video": [
    { type: ' voiceover', text: "Why do 90% of people drift... while 10% dominate? 🎯 It all comes down to one thing: Focus." },
    { type: ' onscreen', text: "Focus is Your Ultimate Superpower ⚡️" },
    { type: ' voiceover', text: "Most chase cheap dopamine. Winners? They chase discipline." },
    { type: ' scene', text: "Phone buzzing on desk, but person keeps deep working without checking it." },
    { type: ' voiceover', text: "Every scroll, every distraction — it costs you your future. 💎" },
    { type: ' onscreen', text: "Discipline = True Freedom ✅" },
    { type: ' voiceover', text: "Imagine one month where every action compounds your future self." },
    { type: ' scene', text: "Morning sunrise run, clean desk, deep focused writing." },
    { type: ' voiceover', text: "You already have the power. It's time to use it." },
    { type: ' cta', text: "Follow for daily focus hacks and discipline upgrades!" },
  ],
  "Value Drop": [
    { type: ' voiceover', text: "Want laser-sharp focus? Master these 3 life-changing habits. 🔥" },
    { type: ' onscreen', text: "Focus Upgrade: 3 Habits 🎯" },
    { type: ' voiceover', text: "1. Morning routine — Control your first hour, control your life. ☀️" },
    { type: ' scene', text: "Making bed, journaling goals, sipping black coffee." },
    { type: ' voiceover', text: "2. Single-tasking — No tabs. No notifications. Just pure flow. 🧠" },
    { type: ' onscreen', text: "Flow State = Unstoppable ✅" },
    { type: ' voiceover', text: "3. Digital detox — Your brain is NOT built for infinite scrolling. 📵" },
    { type: ' scene', text: "Phone screen flipped upside down, turned off during work." },
    { type: ' voiceover', text: "Focus isn't a skill. It's your superpower." },
    { type: ' cta', text: "Follow for real discipline, not motivation quotes." },
  ]
},

"healthy eating on a budget": {
  "Hook Video": [
    { type: ' voiceover', text: "Think eating healthy has to be expensive? Let's destroy that myth. 🍎💥" },
    { type: ' onscreen', text: "Budget Gains 💪" },
    { type: ' voiceover', text: "With smart choices, you can fuel a powerful body — without going broke. 🛒" },
    { type: ' scene', text: "Grocery cart filled with oats, eggs, bananas, chicken — basic affordable staples." },
    { type: ' voiceover', text: "Fancy superfoods are optional. Discipline is not." },
    { type: ' onscreen', text: "Smart Eating = Smart Winning ✅" },
    { type: ' voiceover', text: "Simple meals. Real ingredients. Savage results. 🔥" },
    { type: ' scene', text: "Meal prep: grilled chicken, steamed broccoli, brown rice containers stacked neatly." },
    { type: ' voiceover', text: "You don't need more money. You need a better grocery list." },
    { type: ' cta', text: "Follow for affordable eating hacks to fuel greatness!" },
  ],
  "Value Drop": [
    { type: ' voiceover', text: "3 affordable powerhouse foods every athlete eats on a budget. 💪" },
    { type: ' onscreen', text: "Supercharge Without Overspending ⚡️" },
    { type: ' voiceover', text: "1. Oats — Complex carbs, fiber, energy. Costs pennies per meal. 🥣" },
    { type: ' scene', text: "Oats boiling with cinnamon and banana." },
    { type: ' voiceover', text: "2. Eggs — Pure muscle fuel packed with essential nutrients. 🍳" },
    { type: ' onscreen', text: "Protein Perfection ✅" },
    { type: ' voiceover', text: "3. Rice — Fuel your workouts without draining your wallet. 🍚" },
    { type: ' scene', text: "Rice cooker steaming with a side of chicken." },
    { type: ' voiceover', text: "Consistency beats luxury. Always has. Always will." },
    { type: ' cta', text: "Follow for simple, powerful eating strategies!" },
  ]
}

  };