import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FantasyModeProvider } from "./components/FantasyModeContext";
import { FantasyModeBody } from "./components/FantasyModeBody";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FantasyModeProvider>
        {/* ✅ The actual <body> tag is rendered inside FantasyModeBody */}
        <FantasyModeBody
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white min-h-screen overflow-x-hidden`}
        >
          {children}
        </FantasyModeBody>
      </FantasyModeProvider>
    </html>
  );
}