import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FantasyModeProvider, useFantasyMode } from "./components/FantasyModeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function BodyWithFantasyMode({ children }: { children: React.ReactNode }) {
  const { fantasyMode } = useFantasyMode();

  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-x-hidden ${
        fantasyMode ? "fantasy-mode" : "bg-black text-white"
      }`}
    >
      {children}
    </body>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <FantasyModeProvider>
        <BodyWithFantasyMode>{children}</BodyWithFantasyMode>
      </FantasyModeProvider>
    </html>
  );
}